# Site Settings
title : Short Thoughts
author: 
  name: Nina Zumel
  github: NinaZumel
description: A microblog of my own
baseurl: /short_thoughts
  
show_excerpts : true

# set timezone
timezone: America/Los_Angeles
future: true

theme: minima
