theme: minima

# Site Settings
title : Short Thoughts
title_separator          : "-"
name                     : "Nina Zumel"
description              : "A place for microblogging"

# set timezone
timezone: America/Los_Angeles

