# Site Settings
title : Short Thoughts
#author:
#  name: GitHub User
#  email: your-email@domain.com
author: 
  name: Nina Zumel
url: https://ninazumel.com/short_thoughts
  


show_excerpts : true

# set timezone
timezone: America/Los_Angeles

theme: minima
