# Site Settings
title : Short Thoughts
author: 
  name: Nina Zumel
description: A microblog of my own
baseurl: /short_thoughts
  
show_excerpts : true

# set timezone
timezone: America/Los_Angeles

theme: minima
